cvm-version: 0.0.14
ovmf-version: 0.0.2
cpus: 16
memory: 32768

metrics: 10.0.2.2:6379

models:
  - id: deepseek-r1:70b
    mpk: foo

shim:
  domains:
    - deepseek-r1-70b.model.tinfoil.sh
  listen-port: 443
  upstream-port: 11434
  paths:
    - /v1/chat/completions
    - /v1/embeddings
    - /api/chat
    - /api/generate
    - /api/embed
